UrunSatisSistemi/UrunSatisSistemi/Controllers/SepetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UrunSatisSistemi.Models;

namespace UrunSatisSistemi.Controllers
{
    [Authorize]
    public class SepetController : Controller
    {
        // GET: Sepet
        public ActionResult AnaSepet()
        {
            var x = Baglanti.db.TSepet.ToList();
            return View(x);
        }
        [HttpGet]
        public ActionResult YeniSepet()
        {
            List<SelectListItem> deger = (from x in Baglanti.db.TMusteri.ToList() select new SelectListItem { Text = x.Musteri, Value = x.MusteriID.ToString() }).ToList();
            ViewBag.dgr = deger;
            List<SelectListItem> deger2 = (from x in Baglanti.db.TUrun.ToList() select new SelectListItem { Text = x.Urun, Value = x.UrunID.ToString() }).ToList();
            ViewBag.dgr2 = deger2;
            return View();
        }
        [HttpPost]
        public ActionResult YeniSepet(TSepet t)
        {
            Baglanti.db.TSepet.Add(t);
            Baglanti.db.SaveChanges();
            return RedirectToAction("AnaSepet");
        }
        [HttpGet]
        public ActionResult SepetGuncelle(int id)
        {
            List<SelectListItem> deger = (from x in Baglanti.db.TMusteri.ToList() select new SelectListItem { Text = x.Musteri, Value = x.MusteriID.ToString() }).ToList();
            ViewBag.dgr = deger;
            List<SelectListItem> deger2 = (from x in Baglanti.db.TUrun.ToList() select new SelectListItem { Text = x.Urun, Value = x.UrunID.ToString() }).ToList();
            ViewBag.dgr2 = deger2;
            var x2 = Baglanti.db.TSepet.Find(id);
            return View(x2);
        }
        [HttpPost]
        public ActionResult SepetGuncelle(TSepet m)
        {
            var x = Baglanti.db.TSepet.Find(m.SepetID);
            var urun = Baglanti.db.TUrun.Where(c => c.UrunID == m.TUrun.UrunID).FirstOrDefault();
            var musteri = Baglanti.db.TMusteri.Where(c => c.MusteriID == m.TMusteri.MusteriID).FirstOrDefault();
            x.Urun = urun.UrunID;
            x.Musteri = musteri.MusteriID;
            x.Adet = m.Adet;
            x.ToplamMiktar = m.ToplamMiktar;
            Baglanti.db.SaveChanges();
            return RedirectToAction("AnaSepet");
        }
        public ActionResult SepetSil(int id)
        {
            var x = Baglanti.db.TSepet.Find(id);
            Baglanti.db.TSepet.Remove(x);
            Baglanti.db.SaveChanges();
            return RedirectToAction("AnaSepet");
        }
    }
}

UrunSatisSistemi/UrunSatisSistemi/Views/Sepet/AnaSepet.cshtml
@using UrunSatisSistemi.Models
@model List<TSepet>
@{
    ViewBag.Title = "AnaSepet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />
<h2>Sepet</h2>
<br />
<table class="table table-hover">
    <tr><th>ID</th><th>Müşteri</th><th>Ürün</th><th>Adet</th><th>Toplam Miktar</th><th>İşlemler</th></tr>
    @foreach (var ktg in Model)
    {
        <tr>
            <td>@ktg.SepetID</td>
            <td>@ktg.TMusteri.Musteri</td>
            <td>@ktg.TUrun.Urun</td>
            <td>@ktg.Adet</td>
            <td>@ktg.ToplamMiktar</td>
            <td>
                @Html.ActionLink("Sil", "SepetSil", new { ID = ktg.SepetID }, new { @class = "btn btn-danger", onclick = "return confirm('Silmek İstiyor musunuz?')" })
                <a href="~/Sepet/SepetGuncelle/@ktg.SepetID" class="btn btn-primary">Güncelle</a>
            </td>
        </tr>
    }
</table>
<a href="/Sepet/YeniSepet" class="btn btn-primary">Sepete Yeni İşlem Ekle</a>

UrunSatisSistemi/UrunSatisSistemi/Views/Sepet/SepetGuncelle.cshtml
@model UrunSatisSistemi.Models.TSepet
@{
    ViewBag.Title = "SepetGuncelle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />

<form method="post">
    <h2> Sepet Güncelle</h2>
    <br />
    <div style="margin-top:15px">
        <label>
            Sepet ID
        </label>
        @Html.TextBoxFor(y => y.SepetID, new { @class = "form-control", @required = "required" })
    </div>
    <div style="margin-top:15px">
        <label>
            Müşteri
        </label>
        @Html.DropDownListFor(y => y.TMusteri.MusteriID, (List<SelectListItem>)ViewBag.dgr, "Müşteri Seçiniz..", new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>
            Ürün
        </label>
        @Html.DropDownListFor(y => y.TUrun.UrunID, (List<SelectListItem>)ViewBag.dgr2, "Ürün Seçiniz..", new { @class = "form-control" })
    </div>
    <br />
    <div style="margin-top:15px">
        <label>
            Adet
        </label>
        @Html.TextBoxFor(y => y.Adet, new { @class = "form-control", @required = "required" })
    </div>
    <br />
    <div style="margin-top:15px">
        <label>
            Toplam Miktar
        </label>
        @Html.TextBoxFor(y => y.ToplamMiktar, new { @class = "form-control", @required = "required" })
    </div>
    <br />
    <br />
    <button class="btn btn-primary">Sepete Ekle</button>
</form>

UrunSatisSistemi/UrunSatisSistemi/Views/Sepet/YeniSepet.cshtml
@model UrunSatisSistemi.Models.TSepet
@{
    ViewBag.Title = "YeniSepet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />

@using (Html.BeginForm("YeniSepet", "Sepet", FormMethod.Post))
{
    <h2>Yeni Sepet</h2>
    <br />
    <div style="margin-top:15px">
        <label>
            Müşteri
        </label>
        @Html.DropDownListFor(y => y.Musteri, (List<SelectListItem>)ViewBag.dgr, "Müşteri Seçiniz..", new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>
            Ürün
        </label>
        @Html.DropDownListFor(y => y.Urun, (List<SelectListItem>)ViewBag.dgr2, "Ürün Seçiniz..", new { @class = "form-control" })
    </div>
    <br />
    <div style="margin-top:15px">
        <label>
            Adet
        </label>
        @Html.TextBoxFor(y => y.Adet, new { @class = "form-control", @required = "required" })
    </div>
    <br />
    <div style="margin-top:15px">
        <label>
            Toplam Miktar
        </label>
        @Html.TextBoxFor(y => y.ToplamMiktar, new { @class = "form-control", @required = "required" })
    </div>
    <br />
    <br />
    <button class="btn btn-primary">Sepete Ekle</button>
}