UrunSatisSistemi/UrunSatisSistemi/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UrunSatisSistemi.Models;

namespace UrunSatisSistemi.Controllers
{
    [Authorize]
    public class KategoriController : Controller
    {
        // GET: Kategori
        public ActionResult AnaKategori()
        {
            var x = Baglanti.db.TKategori.ToList();
            return View(x);
        }
        public PartialViewResult KategoriPartial()
        {
            return PartialView();
        }
        [HttpGet]
        public ActionResult YeniKategori()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniKategori(TKategori t)
        {
            Baglanti.db.TKategori.Add(t);
            Baglanti.db.SaveChanges();
            return RedirectToAction("AnaKategori");
        }
        [HttpGet]
        public ActionResult KategoriGuncelle(int id)
        {
            var x = Baglanti.db.TKategori.Find(id);
            return View(x);
        }
        [HttpPost]
        public ActionResult KategoriGuncelle(TKategori m)
        {
            var x = Baglanti.db.TKategori.Find(m.KategoriID);
            x.Kategori = m.Kategori;
            Baglanti.db.SaveChanges();
            return RedirectToAction("AnaKategori");
        }
        public ActionResult KategoriSil(int id)
        {
            var x = Baglanti.db.TKategori.Find(id);
            Baglanti.db.TKategori.Remove(x);
            Baglanti.db.SaveChanges();
            return RedirectToAction("AnaKategori");
        }
    }
}

UrunSatisSistemi/UrunSatisSistemi/Views/Kategori/AnaKategori.cshtml
@using UrunSatisSistemi.Models
@model List<TKategori>
@{
    ViewBag.Title = "AnaKategori";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />
<h2>Kategoriler</h2>
<br />
<table class="table table-hover">
    <tr><th>ID</th><th>Kategori</th><th>İşlemler</th></tr>
    @foreach (var ktg in Model)
    {
        <tr>
            <td>@ktg.KategoriID</td>
            <td>@ktg.Kategori</td>
            <td>
                @Html.ActionLink("Sil", "KategoriSil", new { ID = ktg.KategoriID }, new { @class = "btn btn-danger", onclick = "return confirm('Silmek İstiyor musunuz?')" })
                <a href="~/Kategori/KategoriGuncelle/@ktg.KategoriID" class="btn btn-primary">Güncelle</a>
            </td>
        </tr>
    }
</table>
<button class="btn btn-primary" data-toggle="modal" data-target="#Modal1">
    Yeni Kategori Ekle
</button>
@Html.Action("KategoriPartial", "Kategori")

UrunSatisSistemi/UrunSatisSistemi/Views/Kategori/KategoriGuncelle.cshtml
@model UrunSatisSistemi.Models.TKategori

@{
    ViewBag.Title = "KategoriGuncelle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />
<form method="post">
    <h2>Kategori Güncelle</h2>
    <br />
    <div style="margin-top:15px">
        <label>
            Kategori ID
        </label>
        @Html.TextBoxFor(y => y.KategoriID, new { @class = "form-control", @required = "required" })
    </div>
    <div style="margin-top:15px">
        <label>
            Kategori
        </label>
        @Html.TextBoxFor(y => y.Kategori, new { @class = "form-control", @required = "required" })
    </div>
    <br />
    <br />
    <button class="btn btn-primary">Kategori Bilgilerini Kaydet</button>
</form>

UrunSatisSistemi/UrunSatisSistemi/Views/Kategori/KategoriPartial.cshtml
<div class="modal" id="Modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">Hakkımızda Metin Girişi</h2>
            </div>
            <form method="post" action="/Kategori/YeniKategori">
                <div class="modal-body">
                    <h2>Yeni Kategori</h2>
                    <br />
                    <div style="margin-top:15px">
                        <label>
                            Kategori
                        </label>
                        <input type="text" name="Kategori" class="form-control" />
                    </div>
                    <br />
                    <br />
                    <button class="btn btn-primary">Yeni Kategori Ekle</button>
                </div>
            </form>
        </div>
    </div>
</div>

UrunSatisSistemi/UrunSatisSistemi/Views/Kategori/YeniKategori.cshtml
@model UrunSatisSistemi.Models.TKategori
@{
    ViewBag.Title = "YeniKategori";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />
<form method="post">
    <h2>Yeni Kategori</h2>
    <br />
    <div style="margin-top:15px">
        <label>
            Kategori
        </label>
        @Html.TextBoxFor(y => y.Kategori, new { @class = "form-control", @required = "required" })
    </div>
    <br />
    <br />
    <button class="btn btn-primary">Yeni Kategori Ekle</button>
</form>